// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcfJ31--LpliLl_JaNclXaAuRLn82aN2g',
    appId: '1:735993325759:web:81b44bfc2fbb978d5e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    authDomain: 'fir-demo-74267.firebaseapp.com',
    databaseURL: 'https://fir-demo-74267-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-74267.appspot.com',
    measurementId: 'G-P34Z4CXDE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM1oALqVdy_Um9VUQz177EYILK7-s-Sg0',
    appId: '1:735993325759:android:1a69787054b5382b5e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    databaseURL: 'https://fir-demo-74267-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-74267.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiUmgfveFfBhcoe1-_EEZjF01zjzyqRdg',
    appId: '1:735993325759:ios:13538d2afdf604785e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    databaseURL: 'https://fir-demo-74267-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-74267.appspot.com',
    androidClientId: '735993325759-1854duln9en2a8ipa3vra3lmdg2jrp25.apps.googleusercontent.com',
    iosClientId: '735993325759-qhkr01er1br2c2b2v9duoi7aejj0o00a.apps.googleusercontent.com',
    iosBundleId: 'com.example.practicsflutterallproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiUmgfveFfBhcoe1-_EEZjF01zjzyqRdg',
    appId: '1:735993325759:ios:13538d2afdf604785e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    databaseURL: 'https://fir-demo-74267-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-74267.appspot.com',
    androidClientId: '735993325759-1854duln9en2a8ipa3vra3lmdg2jrp25.apps.googleusercontent.com',
    iosClientId: '735993325759-qhkr01er1br2c2b2v9duoi7aejj0o00a.apps.googleusercontent.com',
    iosBundleId: 'com.example.practicsflutterallproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcfJ31--LpliLl_JaNclXaAuRLn82aN2g',
    appId: '1:735993325759:web:3865f6f5e479072c5e7e0a',
    messagingSenderId: '735993325759',
    projectId: 'fir-demo-74267',
    authDomain: 'fir-demo-74267.firebaseapp.com',
    databaseURL: 'https://fir-demo-74267-default-rtdb.firebaseio.com',
    storageBucket: 'fir-demo-74267.appspot.com',
    measurementId: 'G-GYJGJ9SN7R',
  );
}
